
services:
  backend:
    build: ./backend
    container_name: crm_backend_stage
    restart: always
    ports:
      - "3002:3333"

  frontend:
    build: ./frontend
    container_name: crm_frontend_stage
    restart: always
    ports:
      - "3001:3001"