version: "3.9"

services:
  backend:
    build: ./
    container_name: backend_stage
    restart: always
    expose:
      - "3002"
      - "3333"

  frontend:
    build:
      context: ./client/whatsapp-web-js-client
      args:
        REACT_APP_URL: /
        REACT_APP_RECAPTCHA_SITE_KEY: 6LfPUUgsAAAAAF1UNb5tVs6bDjbcMwQMEYR-eUHw
        REACT_APP_SOCKET_URL: /
    container_name: frontend_stage
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - backend